name: dyeus
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.1
  firebase_auth: ^3.3.16
  cloud_firestore: ^3.1.13
  firebase_core: ^1.21.1
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1

  fluttertoast: ^8.0.9
  sms_autofill: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - images/
